2023-07-28 14:31:43,018 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Current SDK version is 0.15.7
2023-07-28 14:31:43,018 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Configure stats pid to 17448
2023-07-28 14:31:43,018 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Waleed.Kaimkhani\.config\wandb\settings
2023-07-28 14:31:43,019 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Loading settings from D:\workspace\Ml-ops\outputs\2023-07-28\14-31-27\wandb\settings
2023-07-28 14:31:43,019 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-28 14:31:43,019 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-28 14:31:43,019 WARNING MainThread:17448 [wandb_setup.py:_flush():76] Could not find program at train.py
2023-07-28 14:31:43,019 INFO    MainThread:17448 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'train.py'}
2023-07-28 14:31:43,020 INFO    MainThread:17448 [wandb_init.py:_log_setup():507] Logging user logs to D:\workspace\Ml-ops\outputs\2023-07-28\14-31-27\wandb\run-20230728_143143-nlybd12c\logs\debug.log
2023-07-28 14:31:43,020 INFO    MainThread:17448 [wandb_init.py:_log_setup():508] Logging internal logs to D:\workspace\Ml-ops\outputs\2023-07-28\14-31-27\wandb\run-20230728_143143-nlybd12c\logs\debug-internal.log
2023-07-28 14:31:43,020 INFO    MainThread:17448 [wandb_init.py:init():547] calling init triggers
2023-07-28 14:31:43,021 INFO    MainThread:17448 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-28 14:31:43,021 INFO    MainThread:17448 [wandb_init.py:init():596] starting backend
2023-07-28 14:31:43,021 INFO    MainThread:17448 [wandb_init.py:init():600] setting up manager
2023-07-28 14:31:43,033 INFO    MainThread:17448 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-07-28 14:31:43,038 INFO    MainThread:17448 [wandb_init.py:init():606] backend started and connected
2023-07-28 14:31:43,056 INFO    MainThread:17448 [wandb_init.py:init():697] updated telemetry
2023-07-28 14:31:43,061 INFO    MainThread:17448 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-28 14:31:44,587 ERROR   MainThread:17448 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-28 14:31:44,858 ERROR   MainThread:17448 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "D:\workspace\Ml-ops\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "D:\workspace\Ml-ops\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-28 14:31:46,982 WARNING MsgRouterThr:17448 [router.py:message_loop():77] message_loop has been closed
