2023-07-28 14:25:29,763 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Current SDK version is 0.15.7
2023-07-28 14:25:29,764 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Configure stats pid to 43792
2023-07-28 14:25:29,764 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Waleed.Kaimkhani\.config\wandb\settings
2023-07-28 14:25:29,764 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Loading settings from D:\workspace\Ml-ops\outputs\2023-07-28\14-25-11\wandb\settings
2023-07-28 14:25:29,764 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-28 14:25:29,765 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-28 14:25:29,769 WARNING MainThread:43792 [wandb_setup.py:_flush():76] Could not find program at train.py
2023-07-28 14:25:29,769 INFO    MainThread:43792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'train.py'}
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:_log_setup():507] Logging user logs to D:\workspace\Ml-ops\outputs\2023-07-28\14-25-11\wandb\run-20230728_142529-21p8agyc\logs\debug.log
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:_log_setup():508] Logging internal logs to D:\workspace\Ml-ops\outputs\2023-07-28\14-25-11\wandb\run-20230728_142529-21p8agyc\logs\debug-internal.log
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:init():547] calling init triggers
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:init():596] starting backend
2023-07-28 14:25:29,770 INFO    MainThread:43792 [wandb_init.py:init():600] setting up manager
2023-07-28 14:25:29,783 INFO    MainThread:43792 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-07-28 14:25:29,787 INFO    MainThread:43792 [wandb_init.py:init():606] backend started and connected
2023-07-28 14:25:29,813 INFO    MainThread:43792 [wandb_init.py:init():697] updated telemetry
2023-07-28 14:25:29,818 INFO    MainThread:43792 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-28 14:25:31,111 ERROR   MainThread:43792 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-28 14:25:31,571 ERROR   MainThread:43792 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "D:\workspace\Ml-ops\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "D:\workspace\Ml-ops\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-28 14:25:33,908 WARNING MsgRouterThr:43792 [router.py:message_loop():77] message_loop has been closed
